language: python
sudo: false
python:
  - "2.7"
services:
  - couchdb
cache:
  directories:
    - eggs
before_install:
  - pip install setuptools==7.0
  - python2 bootstrap.py
install:
  - bin/buildout -N
script:
  - bin/nosetests
after_success:
  - bin/coveralls
